backend:
  name: git-gateway
  repo: iteam-software/balis
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: splash
    label: Splash
    folder: splash
    create: true
    fields:
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
      - { name: about, label: About, widget: text } 

  - name: contact
    label: Contact
    folder: contact
    create: true
    fields:
      - { name: name, label: Title }
      - { name: title, label: Subtitle }
      - { name: email, label: Email }  
      - { name: phone, label: Phone } 
